// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionBinding } from "./FunctionBinding";
import type { StateSpecification } from "./StateSpecification";

export type OClass = { key: string, description: string | null, state_spec: StateSpecification | null, function_bindings: Array<FunctionBinding>, 
/**
 * Arbitrary key-value options forwarded to the data plane as
 * `ShardMetadata.options`. Recognised keys include
 * `zenoh_event_publish`, `zenoh_event_locality`, and
 * `ws_event_include_values`.
 */
options?: { [key in string]: string }, };
