// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Concrete infrastructure configuration for a specific deployment instance.
 *
 * This is the **per-deployment, low-level** counterpart to `OClass.options`:
 *
 * | Scope | Field | Purpose |
 * |---|---|---|
 * | Class (`OClass.options`) | `zenoh_event_publish`, etc. | Semantic / behavioral — *what the class does* |
 * | Deployment (`OdgmDataSpec`) | `partition_count`, `shard_type`, `log`, … | Concrete / infrastructure — *how it is deployed* |
 *
 * Different deployments of the same class can have different `OdgmDataSpec`
 * values (e.g., one env with `shard_type = "raft"` for strong consistency,
 * another with `shard_type = "mst"` for eventual).
 *
 * **`shard_type` note**: This field is intentionally low-level. In most cases
 * users should express their intent via `OClassDeployment.nfr_requirements`
 * (e.g., `consistency = STRONG`) and let the PM derive the appropriate shard
 * type during deployment scheduling.
 */
export type OdgmDataSpec = { 
/**
 * Logical ODGM collection names to materialize. A minimal CreateCollectionRequest will
 * be generated per name with uniform partition/replica/shard settings.
 * Defaults to `["{package_name}.{class_key}"]` when empty.
 */
collections?: Array<string>, 
/**
 * Desired partition count per collection (>=1). Partitions drive parallelism and hash space.
 */
partition_count?: number | null, 
/**
 * Desired replica count per partition (>=1). PM selects based on availability NFRs.
 */
replica_count?: number | null, 
/**
 * Low-level shard implementation / consistency strategy (e.g. "mst", "raft").
 * Prefer using `OClass.state_spec.consistency_model`; the PM will derive this
 * automatically. Set explicitly only as an advanced override.
 */
shard_type?: string | null, 
/**
 * Mapping of environment (target_env) -> list of ODGM node ids assigned for that env.
 * Populated by the PM during deployment scheduling.
 */
env_node_ids?: { [key in string]: Array<bigint> }, 
/**
 * Optional ODGM log env filter (maps to ODGM_LOG), e.g. "info,openraft=info,zenoh=warn".
 */
log?: string | null, 
/**
 * Per-deployment shard behavior overrides. Keys here have higher precedence than
 * `OClass.options` and are merged on top at deployment time. Use this for
 * capacity/performance tuning that varies by environment:
 * - `batch_size` — operation batch size (default 1000)
 * - `timeout_ms` — operation timeout in ms (default 5000)
 * - `offload_max_pool_size` — max function invocation pool size (default 64)
 * - `pool_max_idle_lifetime` — pool idle timeout in ms (default 30000)
 * - `pool_max_lifetime` — pool connection refresh interval in ms (default 600000)
 * - `enable_metrics` — collect shard-level metrics (default "true")
 */
options?: { [key in string]: string }, };
